import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "@/utils/api";
import { Action, Domain } from "@prisma/client";
import {
  FormControl,
  FormControlLabel,
  FormLabel,
  Radio,
  RadioGroup,
} from "@mui/material";

const Home: NextPage = () => {
  const abilities = api.permission.getAbilities.useQuery();

  return (
    <>
      <Head>
        <title>Permission Model Sample</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {Object.keys(Domain).map((domain) => {
          return (
            <div style={{ margin: 16 }}>
              <FormControl key={domain}>
                <FormLabel id="demo-radio-buttons-group-label">
                  {domain}
                </FormLabel>
                <RadioGroup
                  aria-labelledby="demo-radio-buttons-group-label"
                  name="radio-buttons-group"
                  row
                >
                  {Object.keys(Action).map((action) => (
                    <FormControlLabel
                      key={`${domain}-${action}`}
                      value={action}
                      control={<Radio />}
                      label={action}
                    />
                  ))}
                </RadioGroup>
              </FormControl>
            </div>
          );
        })}
      </main>
    </>
  );
};

export default Home;
